### ISSUE TITLE
Feature Request: Add widget for Sendable Chooser

### ISSUE THREAD

**Issue by pjreiniger** [frc-web-components/app#16]
We use it for selecting autonomous modes, and it is the one feature that we use that isn't supported vs shuffleboard

**Comment by amorygalili** [comment]
Will work on this one today. Should be a simple addition since there's already a Combo Box component. Just need to take that one and remap the props to work with what's in NetworkTables.

**Comment by amorygalili** [comment]
Just created a new build with a `Sendable Chooser` component:

![FRC_Web_Components_TQ7o5AEng1](https://user-images.githubusercontent.com/6786620/219274023-31321e97-dc81-406b-a08b-312133f36745.gif)
